"""empty message

Revision ID: 4e283a02d527
Revises: b71fe41e6057
Create Date: 2022-05-11 00:10:38.178286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e283a02d527'
down_revision = 'b71fe41e6057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('ability', sa.String(), nullable=True))
    op.add_column('data', sa.Column('base_experience', sa.Integer(), nullable=True))
    op.add_column('data', sa.Column('front_shiny', sa.VARCHAR(), nullable=True))
    op.add_column('data', sa.Column('attack_base_stat', sa.Integer(), nullable=True))
    op.add_column('data', sa.Column('defense_base_stat', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'defense_base_stat')
    op.drop_column('data', 'attack_base_stat')
    op.drop_column('data', 'front_shiny')
    op.drop_column('data', 'base_experience')
    op.drop_column('data', 'ability')
    # ### end Alembic commands ###
