"""empty message

Revision ID: b71fe41e6057
Revises: 85caf574ed00
Create Date: 2022-05-10 19:31:25.043683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71fe41e6057'
down_revision = '85caf574ed00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_pokemon',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['data.pokemon_id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_pokemon')
    # ### end Alembic commands ###
